name: ZMK Firmware

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring

jobs:
  build:
#    needs: convert-and-store-keymap
#    uses: ./.github/workflows/user_config_build.yaml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
    with:
      artifact_name: "keymap_layouts"
      parse_args: "charybdis: '-b keymap-drawer/charybdis.yaml'"
      config_path: "keymap-drawer/config.yaml"
      
